##docker/Dockerfile.ui

FROM python:3.11-slim
WORKDIR /frontend
COPY frontend/ /frontend
RUN pip install --upgrade pip && pip install -r /app/requirements.txt
CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
